version: '3.8'

services:
  api:
    build:
      context: ./functions/api
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_database}
    env_file:
      - .env

  database:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
