name: home-infrastructure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-api:
    name: test-api-infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Test API
        run: |
          cd $GITHUB_WORKSPACE
          touch .env && echo "REGION_NAME=us-east-1\nAPI_HOST=api.domain.com" > .env
          make venv
          make test-api
